library(expm); library(Rmpfr)

# An example of the ADMM algorithm for estimating
# the precision matrix generated by the GLasso algorithm

# We begin by generating a sample covariance matrix
n = 10
X = matrix(rnorm(n^2) , nrow = n, ncol = n)
S = t(X)%*%X/n

# And then we set the parameters for the ADMM algorithm
rho       = 0.5
lambda    = 1.7
tolerance = 1e-05
maxiter   = 1000
error     = 1
iter      = 0

Omega_0 = matrix(0, nrow = n, ncol = n)
Z_0     = matrix(1, nrow = n, ncol = n)
V       = matrix(2, nrow = n, ncol = n)

while (error > tolerance & iter < maxiter) {
  
  temp  = eigen(Z_0-(V-S)/rho, symmetric = T)
  U     = temp$vectors
  D     = diag(temp$values, nrow = n)
  Omega = U%*%(D+sqrtm(D^2+diag(4/rho, nrow = n)))%*%t(U)/2
  Omega = zapsmall(Omega, digits = 7)
  
  Z       = pmax(0, 1-lambda/abs(Omega+rho*V))*(Omega+V/rho)
  diag(Z) = diag(Omega+V/rho)
  
  V = V+rho*(Omega-Z)
  
  error = max(norm((Z-Z_0), "F")/norm(Z_0, "F") , norm(Omega-Z, "F")/norm(Omega, "F"))
  iter = iter+1
  
  Omega_0 = Omega
  Z_0     = Z
  
}